# Generated by Django 3.2.4 on 2021-06-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nozzlle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nozzlle_no', models.IntegerField()),
                ('nozzlle_type', models.CharField(choices=[('petrol', 'petrol'), ('Diesel', 'Diesel')], max_length=20)),
                ('remark', models.TextField()),
            ],
        ),
    ]
