# Generated by Django 3.2.4 on 2021-07-10 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzlle_master', '0002_alter_nozzlle_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzlle',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
    ]
