# Generated by Django 3.2.4 on 2021-07-13 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzlle_master', '0003_nozzlle_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzlle',
            name='nozzlle_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
    ]
