# Generated by Django 3.2.4 on 2021-06-29 09:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors_master', '0003_alter_creditors_pending_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('amount', models.IntegerField()),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Banking Transaction', 'Banking Transaction'), ('PhonePay', 'PhonePay'), ('GooglePay', 'GooglePay'), ('Paytm', 'Paytm'), ('UPI', 'UPI')], max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_no', models.IntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('creditors_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='creditors_master.creditors')),
            ],
        ),
    ]
