# Generated by Django 3.2.4 on 2021-07-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors_payment', '0002_payment_reffrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='slip_no',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
