# Generated by Django 3.2.4 on 2021-07-10 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('tea_coffee', models.IntegerField()),
                ('electricity', models.IntegerField()),
                ('water_bill', models.IntegerField()),
                ('stationary', models.IntegerField()),
                ('labour_expense', models.IntegerField()),
                ('property_tax', models.IntegerField()),
                ('maintainence_expense', models.IntegerField()),
                ('machinory_expense', models.IntegerField()),
                ('insurence_expence', models.IntegerField()),
                ('ruff_expense', models.IntegerField()),
                ('employee_insurance_expense', models.IntegerField()),
                ('total_Amount', models.IntegerField()),
                ('remark', models.TextField(max_length=50)),
            ],
        ),
    ]
