# Generated by Django 3.2.4 on 2021-07-15 09:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailybase_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('employee_id', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('employee_name', models.CharField(max_length=30)),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')])),
                ('remark', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
