# Generated by Django 3.2.4 on 2021-06-29 07:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nozzlle_master', '0002_alter_nozzlle_remark'),
        ('vehicle_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='creditor_transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('petrol_in_lit', models.IntegerField(blank=True, null=True)),
                ('diesel_in_lit', models.IntegerField(blank=True, null=True)),
                ('petrol_price', models.IntegerField(blank=True, null=True)),
                ('diesel_price', models.IntegerField(blank=True, null=True)),
                ('remark', models.TextField(max_length=100)),
                ('nozzlle_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_transaction', to='nozzlle_master.nozzlle')),
                ('vehicle_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_transaction', to='vehicle_master.vehicle')),
            ],
        ),
    ]
