# Generated by Django 3.2.4 on 2021-07-13 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors_transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor_transaction',
            name='diesel_in_lit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='creditor_transaction',
            name='diesel_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='creditor_transaction',
            name='petrol_in_lit',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='creditor_transaction',
            name='petrol_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='creditor_transaction',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
