# Generated by Django 3.2.4 on 2021-07-09 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_alter_rate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='oil_stock',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Price should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='diesel_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Price should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='petrol_price',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Price should not be less than 0')]),
        ),
    ]
