# Generated by Django 3.2.4 on 2021-07-13 05:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20210709_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='oil_stock',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
    ]
