# Generated by Django 3.2.4 on 2021-07-02 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('tank_opening', models.IntegerField()),
                ('tank_closing', models.IntegerField()),
                ('total_lit_petrol', models.IntegerField()),
                ('total_lit_diesel', models.IntegerField()),
                ('loss_in_petrol', models.IntegerField()),
                ('loss_in_diesel', models.IntegerField()),
            ],
        ),
    ]
