# Generated by Django 3.2.4 on 2021-07-19 12:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_master', '0002_auto_20210713_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='tank_closing',
        ),
        migrations.RemoveField(
            model_name='calculation',
            name='tank_opening',
        ),
        migrations.AddField(
            model_name='calculation',
            name='tank_closing_diesel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tank_closing_petrol',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tank_opening_diesel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AddField(
            model_name='calculation',
            name='tank_opening_petrol',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='loss_in_diesel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='loss_in_petrol',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_lit_diesel',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='calculation',
            name='total_lit_petrol',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
    ]
