# Generated by Django 3.2.4 on 2021-07-20 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_master', '0003_auto_20210719_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='tank_closing_diesel',
            new_name='tank_lit_diesel',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='tank_closing_petrol',
            new_name='tank_lit_petrol',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='tank_opening_diesel',
            new_name='total_price_diesel',
        ),
        migrations.RenameField(
            model_name='calculation',
            old_name='tank_opening_petrol',
            new_name='total_price_petrol',
        ),
    ]
