# Generated by Django 3.2.4 on 2021-07-01 13:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_master', '0005_alter_employee_date'),
        ('nozzlle_master', '0002_alter_nozzlle_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='nozzlle_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('cash', models.IntegerField()),
                ('phonePay', models.IntegerField()),
                ('googlePay', models.IntegerField()),
                ('paytm', models.IntegerField()),
                ('upi', models.IntegerField()),
                ('total_lit_petrol', models.IntegerField()),
                ('total_lit_diesel', models.IntegerField()),
                ('total_price_petrol', models.IntegerField()),
                ('total_price_diesel', models.IntegerField()),
                ('loss_price_petrol', models.IntegerField()),
                ('loss_price_diesel', models.IntegerField()),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('opening_lit_petrol', models.IntegerField()),
                ('closing_lit_petrol', models.IntegerField()),
                ('Opening_lit_Diesel', models.IntegerField()),
                ('closing_lit_Diesel', models.IntegerField()),
                ('employee_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzlle_t', to='employee_master.employee')),
                ('nozzlle_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nozzlle_t', to='nozzlle_master.nozzlle')),
            ],
        ),
    ]
