# Generated by Django 3.2.4 on 2021-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzlle_transaction', '0002_auto_20210702_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='nozzlle_t',
            name='creditor_amount',
            field=models.IntegerField(default=0),
        ),
    ]
