# Generated by Django 3.2.4 on 2021-07-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nozzlle_transaction', '0006_auto_20210713_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nozzlle_t',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nozzlle_t',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
