# Generated by Django 3.2.4 on 2021-06-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_id', models.IntegerField()),
                ('first_name', models.TextField()),
                ('middle_name', models.TextField()),
                ('last_name', models.TextField()),
                ('Contact_no', models.IntegerField()),
                ('address', models.TextField()),
                ('Street', models.TextField()),
                ('area', models.TextField()),
                ('City', models.TextField()),
                ('state', models.TextField()),
                ('pincode', models.IntegerField()),
                ('Country', models.TextField()),
                ('dob', models.DateField()),
                ('designation', models.TextField()),
                ('gender', models.TextField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('reffrence', models.TextField()),
                ('shift_timming', models.TextField(choices=[('Day-Shift', 'Day-Shift'), ('AfterNoon-Shift', 'AfterNoon-Shift'), ('Night-Shift', 'Night-Shift')], max_length=20)),
                ('education', models.TextField()),
                ('Date_of_join', models.DateField()),
                ('expected_salary', models.IntegerField()),
            ],
        ),
    ]
