# Generated by Django 3.2.4 on 2021-06-25 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0003_auto_20210621_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
    ]
