# Generated by Django 3.2.4 on 2021-07-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0005_alter_employee_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='vaccinated',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20, null=True),
        ),
    ]
