# Generated by Django 3.2.4 on 2021-07-13 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0006_employee_vaccinated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Contact_no',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Pan_Number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_no',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='expected_salary',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value should not be less than 0')]),
        ),
    ]
