# Generated by Django 3.2.4 on 2021-07-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0008_alter_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Document_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='profile'),
        ),
    ]
