# Generated by Django 3.2.4 on 2021-06-28 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditors_master', '0003_alter_creditors_pending_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vehicle_no', models.CharField(max_length=20)),
                ('driver_name', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(choices=[('2 wheeler', '2 wheeler'), ('4 wheeler', '4 wheeler'), ('6 wheeler', '6 wheeler')], max_length=20)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], max_length=20)),
                ('remark', models.TextField(max_length=100)),
                ('creditors_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='creditors_master.creditors')),
            ],
        ),
    ]
