# Generated by Django 3.2.4 on 2021-07-13 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='remark',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
