# Generated by Django 3.2.4 on 2021-06-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditors_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditors',
            name='creation_date',
            field=models.DateField(),
        ),
    ]
