# Generated by Django 3.2.4 on 2021-07-01 12:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_master', '0005_alter_employee_date'),
        ('employee_payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_p',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('amount_dailybase', models.IntegerField(blank=True, null=True)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Banking Transaction', 'Banking Transaction'), ('PhonePay', 'PhonePay'), ('GooglePay', 'GooglePay'), ('Paytm', 'Paytm'), ('UPI', 'UPI')], max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc_code', models.IntegerField(blank=True, null=True)),
                ('cheque_no', models.IntegerField(blank=True, null=True)),
                ('cheque_date', models.DateField(blank=True, default=datetime.datetime.utcnow, null=True)),
                ('reffrence', models.IntegerField(blank=True, default=0, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('employee_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_p', to='employee_master.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
