# Generated by Django 3.2.4 on 2021-07-15 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_dailybase_amount', '0001_initial'),
        ('employee_payment', '0003_auto_20210713_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_p',
            name='amount_dailybase',
        ),
        migrations.AddField(
            model_name='employee_p',
            name='e_dailybase_amount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_p', to='e_dailybase_amount.dailybase_a'),
        ),
    ]
