# Generated by Django 3.2.4 on 2021-06-29 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.utcnow)),
                ('receipt_no', models.IntegerField()),
                ('petrol_in_lit', models.IntegerField()),
                ('diesel_in_lit', models.IntegerField()),
                ('loss_of_petrol_in_lit', models.IntegerField()),
                ('loss_of_diesel_in_lit', models.IntegerField()),
                ('transportation_expense', models.IntegerField()),
            ],
        ),
    ]
