# Generated by Django 3.2.4 on 2021-07-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='oil_in_lit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
