# Generated by Django 3.2.4 on 2021-06-25 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank_master', '0002_auto_20210625_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='diesel_closing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='diesel_opening',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='loss_diesel_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='loss_petrol_price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='petrol_closing',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
        migrations.AlterField(
            model_name='tank',
            name='petrol_opening',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0, 'Salary should not be less than 0')]),
        ),
    ]
